# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sprint_node.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='sprint_node.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x11sprint_node.proto\"6\n\nSprintNode\x12\x14\n\x0cproject_name\x18\x01 \x01(\t\x12\x12\n\ntask_names\x18\x02 \x03(\t\"3\n\x13SprintNodeContainer\x12\x1c\n\x07\x65ntries\x18\x01 \x03(\x0b\x32\x0b.SprintNodeb\x06proto3')
)




_SPRINTNODE = _descriptor.Descriptor(
  name='SprintNode',
  full_name='SprintNode',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='project_name', full_name='SprintNode.project_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='task_names', full_name='SprintNode.task_names', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=21,
  serialized_end=75,
)


_SPRINTNODECONTAINER = _descriptor.Descriptor(
  name='SprintNodeContainer',
  full_name='SprintNodeContainer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='entries', full_name='SprintNodeContainer.entries', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=77,
  serialized_end=128,
)

_SPRINTNODECONTAINER.fields_by_name['entries'].message_type = _SPRINTNODE
DESCRIPTOR.message_types_by_name['SprintNode'] = _SPRINTNODE
DESCRIPTOR.message_types_by_name['SprintNodeContainer'] = _SPRINTNODECONTAINER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SprintNode = _reflection.GeneratedProtocolMessageType('SprintNode', (_message.Message,), dict(
  DESCRIPTOR = _SPRINTNODE,
  __module__ = 'sprint_node_pb2'
  # @@protoc_insertion_point(class_scope:SprintNode)
  ))
_sym_db.RegisterMessage(SprintNode)

SprintNodeContainer = _reflection.GeneratedProtocolMessageType('SprintNodeContainer', (_message.Message,), dict(
  DESCRIPTOR = _SPRINTNODECONTAINER,
  __module__ = 'sprint_node_pb2'
  # @@protoc_insertion_point(class_scope:SprintNodeContainer)
  ))
_sym_db.RegisterMessage(SprintNodeContainer)


# @@protoc_insertion_point(module_scope)
